---
title: "My First Flexdashboard"
output: 
  flexdashboard::flex_dashboard:
    theme: yeti
    #orientation: rows
    source_code: embed
runtime: shiny
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r }
title <- "This is my title"
```

## {.sidebar} 

**How to use**: choose a number, say $b$ using the box below labled "Enter a number". Once done, $100$ random observations from $N(b,1)$ will be generated, and you get:

* a data frame of the generated numbers (repeated 10 times !)
* a summary and
* a Scatter plot.  

You can then introduce a title of your choice for the plot in the text box labled "Type a title". 

```{r}
numericInput(inputId = "inp2a", label = "Enter a number", value = 0)
textInput(inputId = "inp1a", label = "Type a title", value = title)
```

```{r}
X <- reactive({
  m <- input$inp2a 
  rnorm(100, mean = m)
})
```

##

### 

```{r}
renderTable(data.frame(matrix(rep(X(), 10), ncol = 10)))
```

###

```{r}
renderPrint(summary(X()))
```

##

### 

```{r}
renderPlot(plot(X(), main = input$inp1a))
```
